name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main # PRs to the main branch will trigger the workflow
      - development # PRs to the development branch will also trigger the workflow
    paths:
      - "**/*.js" # Only run for changes to JS files or modify this if needed
      - "**/*.json" # Include package.json and package-lock.json changes
      - "app/**/*.js" # Include changes to JavaScript files in the app folder

jobs:
  test:
    runs-on: ubuntu-latest # You can also use other operating systems like windows-latest or macos-latest
    env:
      CI: true # Set this to true for CI environment

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" # Specify the Node.js version you want to use (lts = latest stable version)

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run tests
      - name: Run tests (skip database tests in CI)
        run: npm test --skip-db # Pass a flag to skip database tests
